language: node_js
node_js:
  - 10
  - 12

cache:
  npm: true
  directories:
    - node_modules

# before_script: "npm i coveralls nyc"
# script: "npm run eslint;npx nyc ava"
script: "npx xo;npx ava"
# after_script: "npm run report"

branches:
  only:
    - master
